name: CI/CD Pipeline for Full-Stack App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd task-tracker-backend
          npm install

      # - name: Run backend tests
      #   run: |
      #     cd task-tracker-backend
      #     npm test

      - name: Deploy to Render
        env:
          RENDER_API_TOKEN: ${{ secrets.RENDER_API_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "srv-d1vkhher433s73fp2j40"}' \
            https://api.render.com/v1/services/srv-d1vkhher433s73fp2j40/deploys

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd task-tracker-frontend
          npm install

      - name: Build frontend
        run: |
          cd task-tracker-frontend
          npm run build || echo "Build failed, checking output"

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli
          netlify deploy --prod --site=$NETLIFY_SITE_ID --dir=task-tracker-frontend/build